python GFLOW_ptl_analyzer3.py menom8plume1x_10x.nam
python GFLOW_ptl_analyzer3.py menom8plume1x_5x.nam
python GFLOW_ptl_analyzer3.py menom8plume1x_2x.nam
python GFLOW_ptl_analyzer3.py menom8plume1x_1x.nam
python GFLOW_ptl_analyzer3.py menom8plume1x_0_5x.nam
python GFLOW_ptl_analyzer3.py menom8plume1x_0_2x.nam